#
# $Id: Makefile,v 1.2 2006/01/11 15:31:06 asergey Exp $
#

include ../vsn.mk
include ../../../support/include.mk
ERLC_FLAGS += -I../include

all: $(ERL_OBJECTS)

clean:
	-rm $(ERL_OBJECTS)
